version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../node.dockerfile
    command: npm run dev
    network_mode: host
    # Uncomment the volume portion to mount your own filesystem on 
    # so you dont have to always docker-compose up --rebuild when developing
    # volumes:
    #   - ./frontend/:/app
  user-svc:
    build: 
      context: ./user-service
      dockerfile: ../node.dockerfile
    command: npm run dev
    network_mode: host
  matching-svc:
    build: 
      context: ./matching-service
      dockerfile: ../node.dockerfile
    command: npm run dev
    network_mode: host
  collab-svc:
    build: 
      context: ./collab-service
      dockerfile: ../node.dockerfile
    command: npm run dev
    network_mode: host
  question-svc:
    build:
      context: ./question-service
      dockerfile: ../go.dockerfile
    network_mode: host
  code-runner-svc:
    build:
      context: ./coderunner-service
    network_mode: host
    

