apiVersion: v1
kind: Service
metadata:
  name: {{ include "peerprep.frontend.name" . }}
  labels:
    {{- include "peerprep.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.deployment.ports.name }}
      protocol: TCP
      name: http
  selector:
    {{- include "peerprep.frontend.selectorLabels" . | nindent 4 }}
