ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "DELETE, PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/enable-cors: "true"

  hosts:
    paths:
      - path: /api/user/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-user-svc
            port:
              name: user-svc
      - path: /api/match/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-matching-svc
            port:
              name: matching-svc
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-frontend
            port:
              name: frontend-svc
      - path: /api/coderunner/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-coderunner-svc
            port:
              name: coderunner-svc
      - path: /api/collab/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-collab-svc
            port:
              name: collab-svc
      - path: /api/communication/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-communication-svc
            port:
              name: comm-svc
      - path: /api/question/(.*)
        pathType: Prefix
        backend:
          service:
            name: peerprep-question-svc
            port:
              name: question-svc
      - path: /api/kafka/(.*)
        pathType: Prefix
        backend:
          service:
            name: kafka-1
            port:
              name: kafka-1

frontend:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/frontend
      tag: 1.0.15

    ports:
      name: frontend-svc
      containerPort: 5173

  service:
    type: ClusterIP
    port: 80

user_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/user
      tag: 1.0.3

    ports:
      name: user-svc
      containerPort: 8000

  service:
    type: ClusterIP
    port: 80

matching_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/matching
      tag: 1.0.8

    ports:
      name: matching-svc
      containerPort: 8001

  service:
    type: ClusterIP
    port: 80

coderunner_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/coderunner
      tag: 1.0.3

    ports:
      name: coderunner-svc
      containerPort: 6969

  service:
    type: ClusterIP
    port: 80

collab_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/collab
      tag: 1.0.2

    ports:
      name: collab-svc
      containerPort: 8002

  service:
    type: ClusterIP
    port: 80

communication_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/communication
      tag: 1.0.3

    ports:
      name: comm-svc
      containerPort: 8003

  service:
    type: ClusterIP
    port: 80

question_svc:
  enabled: true
  replicaCount: 1

  deployment:
    image:
      repository: pangpuncake/question
      tag: 1.0.2

    ports:
      name: question-svc
      containerPort: 3000

  service:
    type: ClusterIP
    port: 80
